void irc_addbot(char *host, int port, char *pass);
void irc_init(void);
void irc_free(void);
void irc_announce(char const *, ...);
void irc_topup(void);
void irc_server(void);
void irc_wall(void);
void irc_logo(void);
void irc_topdn(void);
void irc_cps(void);
