/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  529
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.local"
#define VERSION_DATE   "Wed Oct  4 15:53:34 2017"
#define VERSION_STRING "lundman@shinken.local build 529 (Wed Oct  4 15:53:34 2017)"

/* Lundtastic services */
