
	event {
		type = "START";
		format = "Startup: 1Server is now online.";
	};
	event {
		type = "STOP";
		format = "Shutdown: 1%msg%";
	};
	event {
		type = "WALL";
		format = "Wall: <%user%> %msg%";
	};

	event {
		type = "MKD";
		format = "[1%section%] New Release: <15%user%> 1%dir%";
	};
	event {
		type = "RMD";
		format = "[1%section%] Deleted Release: <15%user%> 1%dir%";
	};

	event {
		type = "SFV";
		format = "[1%section%] New SFV File: <15%user%> 1%dir% - %count% files";
	};

	event {
		type = "COMPLETE";
		format = "[1%section%] Completed: <15%user%> 1%dir%";
	};

	event {
		type = "NUKE";
		format = "[1%section%] 0,7Nuke: 1,07%nuker%0,07 on 0,07%dir% at x%multiplier% for: 1%reason%";
	};

	event {
		type = "NUKEE";
		format = "[1%section%] -> 15%user% of 15%group% loses %credits%MB (%files%f %mbytes%mb)";
    };

	event {
		type = "UNNUKE";
		format = "[1%section%] UnNuke: 15%nuker% on 1%dir% at x%multiplier% for: %reason%";
    };

	event {
		type = "UNNUKEE";
		format = "[1%section%] -> 15%user% of 15%group% gains %credits%MB (%files%f %mbytes%mb)";
    };

	event {
		type = "RACEHALF";
		format = "[1%section%] Race Halfway: 1%dir% %half%/%files% files by %racercnt% racer(s) in %mins%m%secs%s. 15%user%@15%group% leads!";
	};

	event {
		type = "RACERSTART";
		format = "[1%section%] New Racer: <15%user%@15%group%> begins 1%dir% at %speed%KB/sec";
	};

	event {
		type = "RACEEND";
		format = "[1%section%] Completed: 1%dir% by %racecnt% racer(s) in %hours%h%min%m%sec%s";
	};

	event {
		type = "RACEREND";
		format = "[1%section%]     [%rank%] 15%user%@15%group% %files%/%total% %speed%KB/sec %megs%MB %percent%%% %time%";
	};

	event {
		type = "RACERNEW";
		format = "[1%section%] New Racer: <15%user%@15%group%> challenges [ %racers% ] on 1%dir% at %speed%KB/sec";
	};

	event {
		type = "MP3GENRE";
		format = "[1%section%] MP3 Genre: <%year%-%genre%> 1%dir%";
	};

	event {
		type = "IMDB";
		format = "[1%section%] IMDb: %url% for 1%dir%";
	};

	event {
		type = "PRE";
		format = "[1%section%] pre: <15%user%@15%group%> 1%dir%";
	};
	event {
		type = "CPS";
		format = "KB/s: %USER% Up: %UP%     Down: %DOWN%    Total: %TOTAL%";
	};

	event {
		type = "MOVE";
        format = "[1%section%-PRE] 1%dir% by <1%user%@1%group%> ";
        };

    event {
        type = "PRE";
        format = "[1%section%] pre: <1%group%> 1%dir%";
        };
	event {
		type = "NEWDAY";
		format = "New Day start. Yesterday's stats: %GBUP% GB, %FUP% files uploaded, %GBDN% GB, %FDN% files downloaded.";
	};
	event {
		type = "UPLTOP";
		format = "[ USER         ] [ FILE                 ] [ MB/s    ] [ MB      ] ";
	};

	event {
		type = "UPLUSER";
		format = "[ %USER% ] [ %FILE% ] [ %UP% ] [ %CURRENT% ]";
	};

	event {
		type = "UPLBOT";
		format = "[ TOTAL        ] [ %TOTAL% Uploaders    ] [ %UP% ] ";
	};
	event {
		type = "DWNTOP";
		format = "[ USER         ] [ FILE                 ] [ MB/s    ] [ MB      ] ";
	};
	event {
		type = "DWNUSER";
		format = "[ %USER% ] [ %FILE% ] [ %DOWN% ] [ %CURRENT% ]";
	};

	event {
		type = "DWNBOT";
		format = "[ TOTAL        ] [ %TOTAL% Downloaders  ] [ %DOWN% ] ";
	};
