
	event {
		type = "START";
		format = "Startup: 04Server is now online.";
	};
	event {
		type = "STOP";
		format = "Shutdown: 04%msg%";
	};
	event {
		type = "WALL";
		format = "Wall: <%user%> %msg%";
	};

	event {
		type = "MKD";
		format = "[04%section%] New Release: <05%user%> 04%dir%";
	};
	event {
		type = "RMD";
		format = "[04%section%] Deleted Release: <05%user%> 04%dir%";
	};

	event {
		type = "SFV";
		format = "[04%section%] New SFV File: <05%user%> 04%dir% - %count% files";
	};

	event {
		type = "COMPLETE";
		format = "[04%section%] Completed: <05%user%> 04%dir%";
	};

	event {
		type = "NUKE";
		format = "[04%section%] 0,7Nuke: 1,07%nuker%0,07 on 0,07%dir% at x%multiplier% for: 04%reason%";
	};

	event {
		type = "NUKEE";
		format = "[04%section%] -> 05%user% of 05%group% loses %credits%MB (%files%f %mbytes%mb)";
    };

	event {
		type = "UNNUKE";
		format = "[04%section%] UnNuke: 05%nuker% on 04%dir% at x%multiplier% for: %reason%";
    };

	event {
		type = "UNNUKEE";
		format = "[04%section%] -> 05%user% of 05%group% gains %credits%MB (%files%f %mbytes%mb)";
    };

	event {
		type = "RACEHALF";
		format = "[04%section%] Race Halfway: 04%dir% %half%/%files% files by %racercnt% racer(s) in %mins%m%secs%s. 05%user%@05%group% leads!";
	};

	event {
		type = "RACERSTART";
		format = "[04%section%] New Racer: <05%user%@05%group%> begins 04%dir% at %speed%KB/sec";
	};

	event {
		type = "RACEEND";
		format = "[04%section%] Completed: 04%dir% by %racecnt% racer(s) in %hours%h%min%m%sec%s";
	};

	event {
		type = "RACEREND";
		format = "[04%section%]     [%rank%] 05%user%@05%group% %files%/%total% %speed%KB/sec %megs%MB %percent%%% %time%";
	};

	event {
		type = "RACERNEW";
		format = "[04%section%] New Racer: <05%user%@05%group%> challenges [ %racers% ] on 04%dir% at %speed%KB/sec";
	};

	event {
		type = "MP3GENRE";
		format = "[04%section%] MP3 Genre: <%year%-%genre%> 04%dir%";
	};

	event {
		type = "IMDB";
		format = "[04%section%] IMDb: %url% for 04%dir%";
	};

	event {
		type = "PRE";
		format = "[04%section%] pre: <05%user%@05%group%> 04%dir%";
	};
	event {
		type = "CPS";
		format = "KB/s: %USER% Up: %UP%     Down: %DOWN%    Total: %TOTAL%";
	};
	event {
		type = "FILLED";
		format = "[%section%] %user% completes request %dir%";
	};
	event {
		type = "NEWDAY";
		format = "New Day start. Yesterday's stats: %GBUP% GB, %FUP% files uploaded, %GBDN% GB, %FDN% files downloaded.";
	};
	event {
		type = "UPLTOP";
		format = "[ USER         ] [ FILE                 ] [ MB/s    ] [ MB      ] ";
	};

	event {
		type = "UPLUSER";
		format = "[ %USER% ] [ %FILE% ] [ %UP% ] [ %CURRENT% ]";
	};

	event {
		type = "UPLBOT";
		format = "[ TOTAL        ] [ %TOTAL% Uploaders    ] [ %UP% ] ";
	};
	event {
		type = "DWNTOP";
		format = "[ USER         ] [ FILE                 ] [ MB/s    ] [ MB      ] ";
	};
	event {
		type = "DWNUSER";
		format = "[ %USER% ] [ %FILE% ] [ %DOWN% ] [ %CURRENT% ]";
	};

	event {
		type = "DWNBOT";
		format = "[ TOTAL        ] [ %TOTAL% Downloaders  ] [ %DOWN% ] ";
	};
