
	event {
		type = "START";
		format = "Startup: 08Server is now online.";
	};
	event {
		type = "STOP";
		format = "Shutdown: 08%msg%";
	};
	event {
		type = "WALL";
		format = "Wall: <%user%> %msg%";
	};

	event {
		type = "MKD";
		format = "[08%section%] New Release: <07%user%> 08%dir%";
	};
	event {
		type = "RMD";
		format = "[08%section%] Deleted Release: <07%user%> 08%dir%";
	};

	event {
		type = "SFV";
		format = "[08%section%] New SFV File: <07%user%> 08%dir% - %count% files";
	};

	event {
		type = "COMPLETE";
		format = "[08%section%] Completed: <07%user%> 08%dir%";
	};

	event {
		type = "NUKE";
		format = "[08%section%] 0,7Nuke: 1,07%nuker%0,07 on 0,07%dir% at x%multiplier% for: 08%reason%";
	};

	event {
		type = "NUKEE";
		format = "[08%section%] -> 07%user% of 07%group% loses %credits%MB (%files%f %mbytes%mb)";
    };

	event {
		type = "UNNUKE";
		format = "[08%section%] UnNuke: 07%nuker% on 08%dir% at x%multiplier% for: %reason%";
    };

	event {
		type = "UNNUKEE";
		format = "[08%section%] -> 07%user% of 07%group% gains %credits%MB (%files%f %mbytes%mb)";
    };

	event {
		type = "RACEHALF";
		format = "[08%section%] Race Halfway: 08%dir% %half%/%files% files by %racercnt% racer(s) in %mins%m%secs%s. 07%user%@07%group% leads!";
	};

	event {
		type = "RACERSTART";
		format = "[08%section%] New Racer: <07%user%@07%group%> begins 08%dir% at %speed%KB/sec";
	};

	event {
		type = "RACEEND";
		format = "[08%section%] Completed: 08%dir% by %racecnt% racer(s) in %hours%h%min%m%sec%s";
	};

	event {
		type = "RACEREND";
		format = "[08%section%]     [%rank%] 07%user%@07%group% %files%/%total% %speed%KB/sec %megs%MB %percent%%% %time%";
	};

	event {
		type = "RACERNEW";
		format = "[08%section%] New Racer: <07%user%@07%group%> challenges [ %racers% ] on 08%dir% at %speed%KB/sec";
	};

	event {
		type = "MP3GENRE";
		format = "[08%section%] MP3 Genre: <%year%-%genre%> 08%dir%";
	};

	event {
		type = "IMDB";
		format = "[08%section%] IMDb: %url% for 08%dir%";
	};

	event {
		type = "PRE";
		format = "[08%section%] pre: <07%user%@07%group%> 08%dir%";
	};
	event {
		type = "CPS";
		format = "KB/s: %USER% Up: %UP%     Down: %DOWN%    Total: %TOTAL%";
	};
	event {
		type = "NEWDAY";
		format = "New Day start. Yesterday's stats: %GBUP% GB, %FUP% files uploaded, %GBDN% GB, %FDN% files downloaded.";
	};
	event {
		type = "UPLTOP";
		format = "[ USER         ] [ FILE                 ] [ MB/s    ] [ MB      ] ";
	};

	event {
		type = "UPLUSER";
		format = "[ %USER% ] [ %FILE% ] [ %UP% ] [ %CURRENT% ]";
	};

	event {
		type = "UPLBOT";
		format = "[ TOTAL        ] [ %TOTAL% Uploaders    ] [ %UP% ] ";
	};
	event {
		type = "DWNTOP";
		format = "[ USER         ] [ FILE                 ] [ MB/s    ] [ MB      ] ";
	};
	event {
		type = "DWNUSER";
		format = "[ %USER% ] [ %FILE% ] [ %DOWN% ] [ %CURRENT% ]";
	};

	event {
		type = "DWNBOT";
		format = "[ TOTAL        ] [ %TOTAL% Downloaders  ] [ %DOWN% ] ";
	};
